#!/usr/bin/env python3
"""
Test script for viewing cube-sphere meshes generated by Agent D
"""
import json
import tempfile
from pathlib import Path

def create_cubesphere_test_scene():
    """Create a test scene that uses the cube-sphere manifest"""
    
    # Path to the generated cube-sphere manifest
    cubesphere_manifest = Path(__file__).parent / "agents/agent_d/mesh/cubesphere_32.json"
    
    scene = {
        "objects": [
            {
                "type": "MESH",
                "pos": [0, 0, 0],
                "manifest": str(cubesphere_manifest),
                "material": "terrain"
            },
            {
                "type": "CUBE",
                "pos": [3, 1, 0],
                "size": [0.5, 0.5, 0.5],
                "material": "reference"
            }
        ],
        "terrain": {
            "type": "sphere",
            "center": [0, 0, 0], 
            "radius": 1.0
        }
    }
    return scene

if __name__ == "__main__":
    # Create test scene
    scene = create_cubesphere_test_scene()
    
    # Write to temporary file
    test_file = Path("/tmp/test_cubesphere_scene.json")
    with open(test_file, 'w') as f:
        json.dump(scene, f, indent=2)
    
    print(f"✅ Cube-sphere test scene created: {test_file}")
    print("🎮 To test the cube-sphere viewer, run:")
    print(f"   python renderer/pcc_game_viewer.py {test_file}")
    print()
    print("🔧 You should see:")
    print("   - A spherical mesh instead of flat grid")
    print("   - F key toggles wireframe to see triangle structure")
    print("   - B key shows bounding box")
    print("   - Reference cube for scale comparison")